### PR TITLE
Make `logo` opaque (white BG)

### PR DESCRIPTION
**Pull request by Rudxain**
fixes https://github.com/zloirock/core-js/pull/1221#issuecomment-1472205278

### CODE REVIEW

**Comment by DreamOfIce** [comment]
To avoid conflicts, I will merge the local changes after committing it

**Comment by stydxm** [comment]
In my opinion, simply make background white is a good solution. It looks dazzling in dark mode. I think Github's solution is a good idea. Its favicon is black in white mode and becomes white in dark mode.

**Comment by Rudxain** [comment]
> I think Github's solution is a good idea. Its favicon is black in white mode and becomes white in dark mode.

Speaking of that, does anyone here have an SVG version of the logo? @zloirock ?

I could use a `<style>` element with a `prefers-color-scheme` media query, to swap colors based on theme

**Comment by DreamOfIce** [comment]
I converted one with the tool and it looks good

**Comment by zloirock** [comment]
I still didn't find it, however, I'm sure that it was present. I'll ask the designer, who made it, this evening.

**Comment by DreamOfIce** [comment]
I added the logo in svg format on commit efa3e4535891dba9e49f0a397bb486ab42b0163a .
However, I couldn't find a way to modify the external svg fill colour via the page's css, so I can only prepare separate logos for the two modes

**Comment by DreamOfIce** [comment]
The logo in svg format looks better and lets me close this pull request.

**Pull request closed without merging**
